# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tumblr-part1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tumblr-part1

    pod 'AlamofireImage'

  target 'tumblr-part1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tumblr-part1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
